apiVersion: v1
kind: Service
metadata:
  name: {{ include "wasmos.fullname" . }}
  labels:
    {{- include "wasmos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wasmos.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
